server:
  port: 8082
spring:
  application:
    name: appointmentService
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_DB
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase: DEBUG

