server:
  port: 8082
jwt:
  secret-key: 1234567890123456789012345678901234567890123456789012345678901234
  access-expiration: 86400000
spring:
  application:
    name: appointmentService
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
    cache:
      type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_DB
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  graphql:
    graphiql:
      enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase: DEBUG

