patient:
  service:
    url: http://patient_service:8081
ai:
  service:
    url: http://ai_service:8085
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/appointment_DB
    username: postgres
    password: 12345678

  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:9092