server:
  port: 8080
jwt:
  secret-key: 1234567890123456789012345678901234567890123456789012345678901234
  access-expiration: 86400000
spring:
  application:
    name: MediTrust
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: patient-route
              uri: http://patient-service:8081
              predicates:
                - Path=/api/v1/patients/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 50
                    redis-rate-limiter.burstCapacity: 50
                    key-resolver: "#{@ipKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: patientCircuitBreaker
                    fallbackUri: forward:/fallback/patient

            - id: appointment-route
              uri: http://appointment-service:8082
              predicates:
                - Path=/api/v1/appointments/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 50
                    redis-rate-limiter.burstCapacity: 50
                    key-resolver: "#{@ipKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: appointmentCircuitBreaker
                    fallbackUri: forward:/fallback/appointment

            - id: file-route
              uri: http://file-service:8088
              predicates:
                - Path=/api/v1/files/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 50
                    redis-rate-limiter.burstCapacity: 50
                    key-resolver: "#{@ipKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: fileCircuitBreaker
                    fallbackUri: forward:/fallback/file

            - id: auth-route
              uri: http://patient-service:8081
              predicates:
                - Path=/api/v1/auth/**

            - id: ai-route
              uri: http://ai-service:8085
              predicates:
                - Path=/api/v1/ai/**

            - id: graphql-route
              uri: http://appointment-service:8082
              predicates:
                - Path=/graphql
  data:
    redis:
      host: redis
      port: 6379
resilience4j:
  circuitbreaker:
    instances:
      patientCircuitBreaker:
        slidingWindowSize: 3
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
      appointmentCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 70
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      fileCircuitBreaker:
        slidingWindowSize: 3
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      appointmentCircuitBreaker:
        timeoutDuration: 10s