server:
  port: 8080
spring:
  application:
    name: MediTrust
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/patients/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 1
                    key-resolver: "#{@ipKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: patientCircuitBreaker
                    fallbackUri: forward:/fallback/patient
            - id: appointment-route
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/appointments/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 3
                    redis-rate-limiter.burstCapacity: 3
                    key-resolver: "#{@ipKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: appointmentCircuitBreaker
                    fallbackUri: forward:/fallback/appointment
            - id: file-route
              uri: http://localhost:8088
              predicates:
                - Path=/api/v1/files/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 3
                    redis-rate-limiter.burstCapacity: 3
                    key-resolver: "#{@ipKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: fileCircuitBreaker
                    fallbackUri: forward:/fallback/file
resilience4j:
  circuitbreaker:
    instances:
      patientCircuitBreaker:
        slidingWindowSize: 3
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
      appointmentCircuitBreaker:
        slidingWindowSize: 3
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
      fileCircuitBreaker:
        slidingWindowSize: 3
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true