server:
  port: 8080
spring:
  application:
    name: MediTrust
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/patient/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 1
                    key-resolver: "#{@ipKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: patientCircuitBreaker
                    fallbackUri: forward:/fallback/patient
resilience4j:
  circuitbreaker:
    instances:
      patientCircuitBreaker:
        slidingWindowSize: 3
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true