server:
  port: 8088

spring:
  application:
    name: file-service

aws:
  s3:
    bucket-name: medi-trust-ai-files-697374140390-eu-north-1-an

  region: eu-north-1

  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}