server:
  port: 8081
jwt:
  secret-key: 1234567890123456789012345678901234567890123456789012345678901234
  access-expiration: 86400000
  refresh-expiration: 604800000
spring:
  application:
    name: patientService
  datasource:
    url: jdbc:postgresql://localhost:5432/patient_data
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase: DEBUG