spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/patient_db
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
patient:
  service:
    url: http://patient_service:8081